# Generated by Django 5.2.16 on 2026-07-14 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Portfolio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("base_currency", models.CharField(max_length=3)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "portfolios",
            },
        ),
        migrations.CreateModel(
            name="PriceHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ticker", models.CharField(max_length=32)),
                ("date", models.DateField()),
                ("close", models.DecimalField(decimal_places=8, max_digits=20)),
            ],
            options={
                "db_table": "price_history",
                "indexes": [
                    models.Index(
                        fields=["ticker", "-date"], name="idx_price_history_ticker_date"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("ticker", "date"), name="uq_price_history_ticker_date"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="VarRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[("historical", "Historical")],
                        default="historical",
                        max_length=32,
                    ),
                ),
                ("confidence", models.FloatField()),
                ("lookback_days", models.PositiveIntegerField()),
                ("as_of_date", models.DateField()),
                ("input_hash", models.CharField(max_length=64, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("complete", "Complete"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "portfolio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="var_runs",
                        to="risk.portfolio",
                    ),
                ),
            ],
            options={
                "db_table": "var_runs",
            },
        ),
        migrations.CreateModel(
            name="VarResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("var_value", models.DecimalField(decimal_places=8, max_digits=20)),
                (
                    "expected_shortfall",
                    models.DecimalField(decimal_places=8, max_digits=20),
                ),
                ("breach_count", models.PositiveIntegerField()),
                ("kupiec_pvalue", models.FloatField()),
                ("computed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "var_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="risk.varrun",
                    ),
                ),
            ],
            options={
                "db_table": "var_results",
            },
        ),
        migrations.CreateModel(
            name="Position",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ticker", models.CharField(max_length=32)),
                ("quantity", models.DecimalField(decimal_places=8, max_digits=20)),
                (
                    "portfolio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="positions",
                        to="risk.portfolio",
                    ),
                ),
            ],
            options={
                "db_table": "positions",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("portfolio", "ticker"),
                        name="uq_position_portfolio_ticker",
                    )
                ],
            },
        ),
    ]
