# Generated by Django 5.2.16 on 2026-07-16 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("risk", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="varrun",
            name="error",
            field=models.TextField(blank=True, null=True),
        ),
    ]
